apiVersion: batch/v1
kind: Job
metadata:
  name: guacamole-initdb
  namespace: guacamole
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: initdb
        image: guacamole/guacamole:1.6.0
        command: ["/bin/sh", "-c"]
        args:
          - /opt/guacamole/bin/initdb.sh --postgresql > /tmp/init.sql;
            cat /tmp/init.sql;