# guacamole/guacamole.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      enableServiceLinks: false
      containers:
        - name: guacamole
          image: guacamole/guacamole:1.5.5
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: guacamole-config-volume
              mountPath: /home/guacamole/.guacamole
              subPath: guacamole.properties
              readOnly: true
      volumes:
        - name: guacamole-config-volume
          configMap:
            name: guacamole-config
            items:
              - key: guacamole.properties
                path: guacamole.properties

---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: guacamole
spec:
  selector:
    app: guacamole
  ports:
    - port: 8080
      targetPort: 8080

